# Generated by Django 5.0.1 on 2024-03-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pationt_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConntryCode', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('geneder', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('patient_type', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('patientid', models.IntegerField()),
                ('dob', models.DateField()),
                ('passportno', models.CharField(max_length=100)),
                ('pannumber', models.BigIntegerField()),
                ('addarnumber', models.BigIntegerField()),
                ('dectorecode', models.IntegerField()),
            ],
        ),
    ]
