# Generated by Django 5.0.1 on 2024-03-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pationt_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contryCode', models.IntegerField()),
                ('Mobail', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastnaem', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('patientType', models.CharField(max_length=100)),
                ('labPatientld', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('patienid', models.IntegerField()),
                ('dob', models.DateField()),
                ('passPortNo', models.CharField(max_length=100, null=True)),
                ('panNumber', models.CharField(max_length=50)),
                ('aadharNumber', models.BigIntegerField()),
                ('insuranceno', models.IntegerField(null=True)),
                ('Appointment', models.DateField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateField()),
                ('paymentType', models.CharField(max_length=50)),
                ('paymentAmount', models.FloatField()),
                ('issueBank', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
