# Generated by Django 5.0.1 on 2024-03-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='issueBank',
        ),
    ]
